config/routes.rb
Rails.application.routes.draw do
  get 'status_updates/show'

  root to: 'activities#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out' => 'devise/sessions#destroy'
  end

  concern :has_roles do
    resources :roles, only: [:new, :create, :destroy]
  end

  concern :impersonatable do
    unless Rails.env.production?
      post 'impersonate', on: :member
      post 'stop_impersonating', on: :collection
    end
  end

  resources :users, except: :new, concerns: [:has_roles, :impersonatable] do
    post 'resend_confirmation_instruction', on: :member
  end
  resources :sources, only: :index
  resources :comments, only: :create
  resources :conferences
  resources :contributors, only: :index
  resources :students, only: :index
  resources :status_updates, only: :show
  resources :status_update_comments, only: :create
  resources :projects do
    get 'receipt', as: :receipt, on: :member
    post 'preview', on: :collection
  end

  get 'rating', to: 'rating/overview#index'
  namespace :rating do
    resources :todos, only: [:index]
    resources :applications, except: [:new, :create, :destroy]
    resources :ratings, only: [:create, :update]
    resources :comments, only: [:create]
  end

  resources :application_drafts, except: [:show, :destroy] do
    member do
      put :apply
      get :check
    end
  end

  get 'apply', to: 'application_drafts#new', as: :apply

  get 'teams/info', to: 'teams_info#index'
  resources :teams do
    resources :join, only: [:new, :create]
    resources :sources
    resources :roles, only: [:new, :create, :destroy]
  end

  resources :roles, only: [] do
    put :confirm, on: :member
  end
  resources :mailings

  get 'calendar/index', as: :calendar
  get 'calendar/events', to: 'calendar#events'

  get 'pages/:page', to: 'pages#show', as: :page

  get 'orga/users/info', to: 'orga/users_info#index', as: :orga_users_info
  patch 'orga/seasons/switch_phase', to: 'orga/seasons#switch_phase', as: :switch_phase
  namespace :orga do
    root to: 'dashboard#index', as: :dashboard
    resources :projects, only: [:index] do
      member do
        put :accept
        put :start_review
        put :reject
        put :lock
        put :unlock
      end
    end
    resources :teams
    resources :seasons
    resources :conferences, except: [:new, :edit, :create] do
      collection { post :import }
    end
    resources :exports, only: [:index, :create]
    resources :mailings do
      resources :submissions
    end
  end

  namespace :students do
    resources :status_updates, :except => [:new] do
      post 'preview', on: :collection
    end
  end

  get 'supervisor', to: 'supervisor/dashboard#index'
  patch 'supervisor/notes', to: 'supervisor/notes#update'
  namespace :supervisor do
    get 'dashboard', to: 'dashboard#index'
    resources :comments, only: [:index, :create]
  end

  namespace :mentor do
    resources :applications, only: [:index, :show] do
      member do
        put :fav
        put :signoff
      end
    end
    resources :comments, only: [:create, :update]
  end

  # get 'activities(.:format)', to: 'activities#index', as: :activities
  get 'activities(/page/:page)(.:format)', to: 'activities#index', as: :activities
end

app/controllers/status_updates_controller.rb
class StatusUpdatesController < ApplicationController
  def show
    @status_update = Activity.with_kind('status_update').find params[:id]
  end
end

app/controllers/students/status_updates_controller.rb
class Students::StatusUpdatesController < Students::BaseController
  before_action :find_resource, only: [:show, :edit, :update, :destroy]
  helper_method :status_updates

  def index
    @status_update = current_team.status_updates.build
  end

  def create
    @status_update = current_team.status_updates.build(
      status_update_params.merge(published_at: Time.now.utc)
    )
    if @status_update.save
      flash[:notice] = 'Status Update created'
      redirect_to action: :index
    else
      render :index
    end
  end

  def preview
    @status_update = current_team.status_updates.build(status_update_params)
    render partial: "preview"
  end

  def show
  end

  def edit
  end

  def update
    if @status_update.update(status_update_params)
      flash[:notice] = 'Status Update updated'
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    if @status_update.destroy
      flash[:notice] = 'Status Update has been deleted'
    else
      flash[:alert]  = 'An error occurred while deleting your status update'
    end
    redirect_to action: :index
  end


  protected

  def find_resource
    @status_update = current_team.status_updates.find params[:id]
  end

  def status_update_params
    params.require(:activity).permit(:title, :content)
  end


  private

  def status_updates
    #order = DESC; set in model
    @status_updates ||= current_team.status_updates.ordered
  end

end

app/views/status_updates/show.html.slim
= content_for :head do
  link rel="alternate" type="application/atom+xml" title="#{@status_update.team.display_name}'s Status Updates" href=activities_url(format: :atom, team_id: @status_update.team_id)
= content_tag :h1, @status_update.title

p
  Published #{l @status_update.published_at, format: :long} 
  by #{link_to @status_update.team.display_name, @status_update.team}

  = link_to activities_path(format: :atom, team_id: @status_update.team.id), class: 'atom' do
    | Subscribe to this teams's activities

.well.status_update
  = render_markdown(@status_update.content).html_safe

h2#comments.header
  = icon('comments')
  span Comments

- if current_user
  = simple_form_for Comment.new(commentable: @status_update), url: status_update_comments_path do |f|
    .checks
      = f.error_notification

      .form-inputs.clearfix
        = f.input :commentable_id, as: :hidden
        = f.input :commentable_type, as: :hidden
        = f.input :text, as: :text, label: "Add a comment", input_html: { rows: 2 }, hint: 'You can use basic <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a> here.'.html_safe, required: true

      .form-actions
        = f.button :submit, 'Save comment'
- else
  p You must be logged in to add a comment.

- @status_update.comments.each do |comment|
  h5 = "#{ user_for_comment(comment) }, #{ l(comment.created_at, format: :shortest) }".html_safe
  p = render_markdown(comment.text).html_safe


nav.page
  .back-nav
    ul
      li = icon('chevron-left')
      li = link_to 'All activities', root_path, class: 'back'

- content_for :title do
  = @status_update.title