config/routes.rb
Rails.application.routes.draw do
  get 'status_updates/show'

  root to: 'activities#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out' => 'devise/sessions#destroy'
  end

  concern :has_roles do
    resources :roles, only: [:new, :create, :destroy]
  end

  concern :impersonatable do
    unless Rails.env.production?
      post 'impersonate', on: :member
      post 'stop_impersonating', on: :collection
    end
  end

  resources :users, except: :new, concerns: [:has_roles, :impersonatable] do
    post 'resend_confirmation_instruction', on: :member
  end
  resources :sources, only: :index
  resources :comments, only: :create
  resources :conferences
  resources :contributors, only: :index
  resources :students, only: :index
  resources :status_updates, only: :show
  resources :status_update_comments, only: :create
  resources :projects do
    get 'receipt', as: :receipt, on: :member
    post 'preview', on: :collection
  end

  get 'rating', to: 'rating/overview#index'
  namespace :rating do
    resources :todos, only: [:index]
    resources :applications, except: [:new, :create, :destroy]
    resources :ratings, only: [:create, :update]
    resources :comments, only: [:create]
  end

  resources :application_drafts, except: [:show, :destroy] do
    member do
      put :apply
      get :check
    end
  end

  get 'apply', to: 'application_drafts#new', as: :apply

  get 'teams/info', to: 'teams_info#index'
  resources :teams do
    resources :join, only: [:new, :create]
    resources :sources
    resources :roles, only: [:new, :create, :destroy]
  end

  resources :roles, only: [] do
    put :confirm, on: :member
  end
  resources :mailings

  get 'calendar/index', as: :calendar
  get 'calendar/events', to: 'calendar#events'

  get 'pages/:page', to: 'pages#show', as: :page

  get 'orga/users/info', to: 'orga/users_info#index', as: :orga_users_info
  patch 'orga/seasons/switch_phase', to: 'orga/seasons#switch_phase', as: :switch_phase
  namespace :orga do
    root to: 'dashboard#index', as: :dashboard
    resources :projects, only: [:index] do
      member do
        put :accept
        put :start_review
        put :reject
        put :lock
        put :unlock
      end
    end
    resources :teams
    resources :seasons
    resources :conferences, except: [:new, :edit, :create] do
      collection { post :import }
    end
    resources :exports, only: [:index, :create]
    resources :mailings do
      resources :submissions
    end
  end

  namespace :students do
    resources :status_updates, :except => [:new] do
      post 'preview', on: :collection
    end
  end

  get 'supervisor', to: 'supervisor/dashboard#index'
  patch 'supervisor/notes', to: 'supervisor/notes#update'
  namespace :supervisor do
    get 'dashboard', to: 'dashboard#index'
    resources :comments, only: [:index, :create]
  end

  namespace :mentor do
    resources :applications, only: [:index, :show] do
      member do
        put :fav
        put :signoff
      end
    end
    resources :comments, only: [:create, :update]
  end

  # get 'activities(.:format)', to: 'activities#index', as: :activities
  get 'activities(/page/:page)(.:format)', to: 'activities#index', as: :activities
end

app/models/conference.rb
require 'csv'
class Conference < ActiveRecord::Base
  REGION_LIST = [
    "Africa",
    "South America",
    "North America",
    "Europe",
    "Asia Pacific"
  ]

  include HasSeason

  has_many :conference_preferences, dependent: :destroy
  has_many :attendees, through: :conference_preferences, source: :team

  validates :name, :url, :city, :country, :region, presence: true

  validate :chronological_dates, if: proc { |conf| conf.starts_on && conf.ends_on }

  accepts_nested_attributes_for :conference_preferences

  scope :ordered, ->(sort = {}) { order([sort[:order] || 'starts_on, name', sort[:direction] || 'asc'].join(' ')) }
  scope :in_current_season, -> { where(season: Season.current) }

  def date_range
    @date_range ||= DateRange.new(start_date: starts_on, end_date: ends_on)
  end

  def chronological_dates
    unless starts_on <= ends_on
      errors.add(:ends_on, 'must be a later date than start date')
    end
  end

  def tickets_left
    confirmed_attendances = conference_preferences.select { |conference_preferences| conference_preferences.confirmed }
    tickets.to_i - confirmed_attendances.size
  end
end

app/models/conference/importer.rb
require 'csv'
class Conference::Importer

  ## This importer is depending on agreed-upon input format.
  ## Input file:
  # - Dates should be formatted with dd mm yyyy
  # - UID should be unique and formatted with season + id: 2017001
  # - The headers should not be changed
  # Output:
  # - Conferences will be updated or created
  # - Conferences deleted in the input file, are not removed from the table
  # - Import errors are logged in a Rails Logger
  # - UID is mapped to 'gid' ('google-id' LOL), and has the format: 2017001

  class << self
    def call(filename, content_type:)
      raise ArgumentError, "Oops! I can upload .csv only :-(" unless content_type == "text/csv"
      new(filename)
    end

    private :new
  end

  def initialize(filename)
    @filename = filename
    with_log { process_csv }
  end

  attr_reader :filename

  def with_log
    logger.tagged("Importer") { logger.info "Started importing conference file" }
    yield
    logger.tagged("Importer") { logger.info "Finished updating/creating #{conferences_count} conferences" }
  end

  def logger
    Rails.logger
  end

  def conferences_count
    CSV.foreach(filename, headers: true).count
  end

  def fetch_season_id(uid)
    # uid format : 2017001
    year = uid.to_s[0,4]
    Season.find_or_create_by!(name: year).id
  end

  def process_csv
    CSV.foreach(filename, headers: true, col_sep: ',' ) do |row|
      begin
        conference = Conference.find_or_initialize_by(gid: row['UID'])
        conference_attributes = {
          name: row['Name'],
          starts_on: row['Start date'],
          ends_on: row['End date'],
          city: row['City'],
          country: row['Country'],
          region: row['Region'],
          url: row['Website'],
          notes: row['Notes'],
        }.merge(season_id: fetch_season_id(conference.gid))
        conference.update!(conference_attributes)
      rescue => e
        logger.tagged("Importer") { logger.error "Error in #{row['UID']}: #{e.message}" }
      end
    end
  end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :confirm_role, except: [:index, :show]

  def new
    @conference = Conference.new
  end

  def index
    @conferences = conferences
  end
 
  def show
    @conference = Conference.find(params[:id])
  end

  def create
    team = current_user.student_team
    @conference = Conference.new(conference_params)
    @conference.season_id = current_season.id
    @conference.gid = generate_gid(team)

    if @conference.save
      redirect_to edit_team_path(team), notice: 'Conference was successfully created.'
    else
      render action: :new
    end
  end

  def redirect
    redirect_to orga_conferences_path
  end

  private

  def generate_gid(team)
    "#{Season.current.name}-#{Time.now.getutc.to_i}-#{team.id}"
  end
 
  def conferences
    Conference.ordered(sort_params).in_current_season
  end

  def conference_params
    params.require(:conference).permit(
      :name, :twitter, :starts_on, :ends_on, :notes, :country, :region, :location, :city, :url
    )
  end

  def confirm_role
    redirect unless current_user.admin? || current_user.student?
  end

  def sort_params
    {
      order: %w(name gid starts_on city country region).include?(params[:sort]) ? params[:sort] : nil,
      direction: %w(asc desc).include?(params[:direction]) ? params[:direction] : nil
    }
  end
end

app/controllers/orga/conferences_controller.rb
class Orga::ConferencesController < Orga::BaseController
  before_action :find_conference, only: [:show, :destroy]

  def import
    Conference::Importer.call(params[:file].path, content_type: params[:file].content_type)
    redirect_to orga_conferences_path, notice: "Import finished! Check log for errors."
  end

  def index
    @conferences = conferences
  end

  def destroy
    @conference.destroy!
    redirect_to orga_conferences_path, notice: 'The conference has been deleted.'
  end

  private

  def find_conference
    @conference ||= Conference.find(params[:id])
  end

  def conferences
    Conference.ordered(sort_params).in_current_season
  end

  def conference_params
    params.require(:conference).permit(
      :name, :location, :city, :country, :region,
      :url, :twitter,
      :starts_on, :ends_on,
      :round, :lightningtalkslots, :tickets, :flights, :accomodation,
      :gid, #id in orga's Google Spreadsheet (format: 2017001)
      :notes,
      conference_preferences_attributes: [:id, :_destroy]
    )
  end

  def sort_params
    {
      order: %w(name gid starts_on city country region).include?(params[:sort]) ? params[:sort] : nil,
      direction: %w(asc desc).include?(params[:direction]) ? params[:direction] : nil
    }
  end

  def set_breadcrumbs
    super
    @breadcrumbs << [ 'Conferences', :conferences]
  end
end

app/views/conferences/_details.html.slim
.conference
  dl.dl-horizontal
    dt Location
    dd #{@conference.city}, #{@conference.country}
    dt Date
    dd = @conference.date_range
    dt Twitter
    dd = format_conference_twitter(@conference.twitter)
    dt Homepage
    -if @conference.url.present?
      dd = link_to @conference.url, @conference.url
    dt Notes
    dd = @conference.notes

app/views/conferences/_table.html.erb
<h1 class="header">Conferences</h1>
<table class="table-striped table-bordered table-condensed conferences">
  <thead>
  <tr>
    <th><%= sortable :name, "Conference" %></th>
    <th><%= sortable :starts_on, "Dates" %></th>
    <th><%= sortable :city %></th>
    <th><%= sortable :country %></th>
    <th><%= sortable :region %></th>
    <th><%= :url %></th>
    <th><%= :notes%></th>
    <th><%= sortable :gid%></th>
  </tr>
  </thead>
  <tbody>
  <% conferences.each do |conference| %>
      <tr>
        <td><%= link_to conference.name, [namespace, conference] %></td>
        <td><%= conference.date_range %></td>
        <td><%= conference.city %></td>
        <td><%= conference.country %></td>
        <td><%= conference.region %></td>
        <td><%= link_to conference.url, conference.url if conference.url.present? %></td>
        <td><%= conference.notes %></td>
        <td><%= conference.gid %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
<p><%= link_to "View as Calendar", calendar_path %></p>

app/views/conferences/index.html.slim
= render 'conferences/table', namespace: nil, conferences: @conferences

app/views/conferences/new.html.slim
nav.page
  .back-nav
    ul
      li = icon('chevron-left')
      li = link_to 'Conferences', conferences_path, class: 'back'

h1.page-header Create a new conference

= simple_nested_form_for @conference do |f|
  - if @conference.errors.any?
    .alert.alert-danger
      h4 = "#{pluralize(@conference.errors.count, "error")} prohibited this conference from being saved:"
      ul
        - @conference.errors.full_messages.each do |message|
          li = message

  .page-header
   h2 Conference info
  fieldset
   = f.input :name, required: true,placeholder: 'Conference name', wrapper_html: { class: 'col-md-12' }
   = f.input :url, required: true, placeholder: 'Conference website', wrapper_html: { class: 'col-md-12' }
   = f.input :twitter, placeholder: '@', wrapper_html: { class: 'col-md-12' }
   = f.input :starts_on, as: :date, html5: true, required: true, label: 'Conference start date', wrapper_html: { class: 'col-md-6' }
   = f.input :ends_on, as: :date, html5: true, required: true, label: 'Conference end date', wrapper_html: { class: 'col-md-6' }
   = f.input :notes, label: 'Conference notes', wrapper_html: { class: 'col-md-12' }

  .page-header
   h2 Conference location
  fieldset
    = f.input :country, required: true, as: :country, prompt: "Conference country", wrapper_html: { class: 'col-md-12' }
    = f.input :region, required: true, collection: Conference::REGION_LIST, prompt: 'Conference region', wrapper_html: { class: 'col-md-12' }
    = f.input :city, required: true, placeholder: 'Conference city', wrapper_html: { class: 'col-md-12' }
   
  .actions
    ul.list-inline
      li = f.submit 'Save', class: 'btn btn-success'

app/views/conferences/show.html.slim
nav.page
  .back-nav
    ul
      li = icon('chevron-left')
      li = link_to 'All conferences', conferences_path, class: 'back'

h1 class="conference" = @conference.name

= render 'conferences/details', namespace: nil, conferences: @conferences