config/routes.rb
Rails.application.routes.draw do
  get 'status_updates/show'

  root to: 'activities#index'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    delete 'sign_out' => 'devise/sessions#destroy'
  end

  concern :has_roles do
    resources :roles, only: [:new, :create, :destroy]
  end

  concern :impersonatable do
    unless Rails.env.production?
      post 'impersonate', on: :member
      post 'stop_impersonating', on: :collection
    end
  end

  resources :users, except: :new, concerns: [:has_roles, :impersonatable] do
    post 'resend_confirmation_instruction', on: :member
  end
  resources :sources, only: :index
  resources :comments, only: :create
  resources :conferences
  resources :contributors, only: :index
  resources :students, only: :index
  resources :status_updates, only: :show
  resources :status_update_comments, only: :create
  resources :projects do
    get 'receipt', as: :receipt, on: :member
    post 'preview', on: :collection
  end

  get 'rating', to: 'rating/overview#index'
  namespace :rating do
    resources :todos, only: [:index]
    resources :applications, except: [:new, :create, :destroy]
    resources :ratings, only: [:create, :update]
    resources :comments, only: [:create]
  end

  resources :application_drafts, except: [:show, :destroy] do
    member do
      put :apply
      get :check
    end
  end

  get 'apply', to: 'application_drafts#new', as: :apply

  get 'teams/info', to: 'teams_info#index'
  resources :teams do
    resources :join, only: [:new, :create]
    resources :sources
    resources :roles, only: [:new, :create, :destroy]
  end

  resources :roles, only: [] do
    put :confirm, on: :member
  end
  resources :mailings

  get 'calendar/index', as: :calendar
  get 'calendar/events', to: 'calendar#events'

  get 'pages/:page', to: 'pages#show', as: :page

  get 'orga/users/info', to: 'orga/users_info#index', as: :orga_users_info
  patch 'orga/seasons/switch_phase', to: 'orga/seasons#switch_phase', as: :switch_phase
  namespace :orga do
    root to: 'dashboard#index', as: :dashboard
    resources :projects, only: [:index] do
      member do
        put :accept
        put :start_review
        put :reject
        put :lock
        put :unlock
      end
    end
    resources :teams
    resources :seasons
    resources :conferences, except: [:new, :edit, :create] do
      collection { post :import }
    end
    resources :exports, only: [:index, :create]
    resources :mailings do
      resources :submissions
    end
  end

  namespace :students do
    resources :status_updates, :except => [:new] do
      post 'preview', on: :collection
    end
  end

  get 'supervisor', to: 'supervisor/dashboard#index'
  patch 'supervisor/notes', to: 'supervisor/notes#update'
  namespace :supervisor do
    get 'dashboard', to: 'dashboard#index'
    resources :comments, only: [:index, :create]
  end

  namespace :mentor do
    resources :applications, only: [:index, :show] do
      member do
        put :fav
        put :signoff
      end
    end
    resources :comments, only: [:create, :update]
  end

  # get 'activities(.:format)', to: 'activities#index', as: :activities
  get 'activities(/page/:page)(.:format)', to: 'activities#index', as: :activities
end

app/models/project.rb
class Project < ActiveRecord::Base
  include HasSeason

  belongs_to :submitter, class_name: 'User'
  has_many :comments, -> { order('created_at DESC') }, as: :commentable, dependent: :destroy

  has_many :first_choice_application_drafts,  class_name: 'ApplicationDraft', foreign_key: 'project1_id'
  has_many :second_choice_application_drafts, class_name: 'ApplicationDraft', foreign_key: 'project2_id'

  validates :name, :submitter, :mentor_email, presence: true

  scope :in_current_season, -> do
    where(season: Season.transition? ? Season.succ : Season.current)
  end

  before_validation :sanitize_url

  include AASM

  aasm whiny_transitions: false do
    state :proposed, initial: true
    state :accepted
    state :rejected
    state :pending

    event :start_review do
      transitions from: :proposed, to: :pending
    end

    event :accept do
      transitions from: :pending, to: :accepted
    end

    event :reject do
      transitions from: :pending, to: :rejected, after: -> { self.comments_locked = true }
    end
  end

  def self.selected
    project_names = Team.in_current_season.accepted.pluck(:project_name)
    Project.in_current_season.accepted.where(name: project_names)
  end

  def taglist
    tags.join(', ')
  end

  def taglist=(taglist)
    self.tags = taglist.split(',').map(&:strip).reject(&:blank?)
  end

  def to_param
    "#{id}-#{name}".parameterize
  end

  def subscribers
    [submitter, mentor, comments.map(&:user)].flatten.uniq
  end

  # FIXME Remove me after https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/342
  class NullMentor
    attr_reader :email, :github_handle
    def initialize(project)
      @email = project.mentor_email.to_s.downcase
      @github_handle = project.mentor_github_handle.to_s.downcase
    end
    def eql?(user)
      user.github_handle.to_s.downcase == github_handle
    end
  end

  def mentor
    @mentor ||= begin
                  _mentor = NullMentor.new(self)
                  if _mentor.eql? submitter
                    submitter
                  else
                    _mentor
                  end
                end
  end

  private

  def sanitize_url
    self.url = "http://#{url}" unless url =~ %r{\Ahttp[s]?://}
  end
end

app/controllers/orga/projects_controller.rb
class Orga::ProjectsController < Orga::BaseController
  before_action :find_resource, except: [:index]

  def index
    @projects = Project.in_current_season
  end

  def accept
    if @project.accept!
      flash[:notice] = "Project has been accepted!"
    else
      flash[:alert]  = "There has been an error accepting this project."
    end
    redirect_to [:orga, :projects]
  end

  def start_review
    if @project.start_review!
      flash[:notice] = "Successfully marked project as pending!"
    else
      flash[:alert]  = "There has been an error marking this project as pending."
    end
    redirect_to [:orga, :projects]
  end

  def reject
    if @project.reject!
      flash[:notice] = "Project has been rejected!"
    else
      flash[:alert]  = "There has been an error rejecting this project."
    end
    redirect_to [:orga, :projects]
  end

  def lock
    @project.update_attribute :comments_locked, true
    redirect_to [:orga, :projects], notice: "Comments for '#{@project.name}' are now locked."
  end

  def unlock
    @project.update_attribute :comments_locked, false
    redirect_to [:orga, :projects], notice: "Comments for '#{@project.name}' are now unlocked."
  end

  private

  def find_resource
    @project ||= Project.find(params[:id])
  end

  def set_breadcrumbs
    super
    @breadcrumbs << [ 'Projects', :projects]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :soft_login_required, only: [:new]
  before_action :check_date!, only: [:new, :create]

  load_and_authorize_resource only: [:edit, :update, :destroy]

  def new
    submitter = current_user || User.new

    @project = Project.new(
      mentor_name: submitter.name,
      mentor_github_handle: submitter.github_handle,
      mentor_email: submitter.email
    )
  end

  def show
    @project = Project.find params[:id]
  end

  def edit
    render :new
  end

  def index
    if Season.current.active?
      @projects = Project.selected
    else
      @projects = Project.in_current_season.where(aasm_state: %w(accepted proposed))
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully deleted'
  end

  def create
    @project = Project.new(project_params)

    @project.submitter = current_user
    @project.season = Season.transition? ? Season.succ : Season.current
    respond_to do |format|
      if @project.save
        ProjectMailer.proposal(@project).deliver_later
        format.html { redirect_to receipt_project_path(@project) }
      else
        format.html { render action: :new }
      end
    end
  end

  def preview
    @project = Project.new(project_params)
    render partial: "preview"
  end

  def receipt
    @project = Project.find(params[:id])
  end

  def update
    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
      else
        format.html { render action: :new }
      end
    end
  end

  private

  def soft_login_required
    store_location key: :previous_url_login_required
  end

  def check_date!
    redirect_to root_path, alert: 'Project submissions are closed.' and return \
      unless Season.projects_proposable?
  end

  def project_params
    params.require(:project).permit(
      :name, :mentor_name, :mentor_github_handle, :mentor_email,
      :url, :code_of_conduct, :description, :issues_and_features, :beginner_friendly,
      :taglist, :source_url, :requirements, :license
    )
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def project_status(project)
    label_class = case project.aasm_state
                  when 'proposed'
                    'label-default'
                  when 'accepted'
                    'label-success'
                  when 'rejected'
                    'label-danger'
                  when 'pending'
                    'label-warning'
                  end
    content_tag :span, project.aasm_state, class: "label #{label_class}"
  end

  def project_tags(project)
    project.tags.map{ |t| "<span class='label label-default'>#{t}</span>" }.join(' ').html_safe
  end

end

app/views/projects/_login_required.html.erb
<div id="login-required-overlay">

  <div class="well">
    <h1>Login Required</h1>
    <p>This action on the RGSoC Teams App requires a user account.</p>
    <p>
      <%= link_to user_github_omniauth_authorize_path, class: "btn btn-primary btn-lg" do %>
        <i class="icon-github"></i>&nbsp;Login with Github
      <% end %>
      <%= link_to "Cancel", root_path, class: "btn btn-lg" %>
    </p>
  </div>

</div>

app/views/projects/_preview.html.slim
h1#preview_project_name
  = @project.name

table.table.table-striped.table-bordered
  tr
    th Mentor
    td
      = @project.mentor_name
      = " ("
      = link_to @project.mentor_github_handle, "https://github.com/#{@project.mentor_github_handle}", class: 'github'
      |)
  tr
    th Project Website
    td = link_to @project.url, @project.url
  tr
    th Project Repository
    td = link_to @project.source_url, @project.source_url
  tr
    th Suitable for Beginners?
    td = @project.beginner_friendly? ? 'yes' : 'no'
  tr
    th Tags
    td = project_tags @project
  tr
    th State
    td = project_status(@project)
  tr
    th Applications (1st Choice)
    td = @project.first_choice_application_drafts.count
  tr
    th Applications (2nd Choice)
    td = @project.second_choice_application_drafts.count
  tr
    th Code of Conduct 
    td = link_to @project.code_of_conduct, @project.code_of_conduct
  tr
    th License
    td = @project.license

h2.header
  = icon('file')
  span Project Description
- if @project.description
  .projects
    p = render_markdown(@project.description).html_safe

h2.header
  = icon('check')
  span Project's Requirements
- if @project.requirements
  .projects
    p = render_markdown(@project.requirements).html_safe

h2.header
  = icon('list')
  span = Project.human_attribute_name(:issues_and_features).titleize
- if @project.issues_and_features
  .projects
    p = render_markdown(@project.issues_and_features).html_safe

app/views/projects/index.html.slim
- if Season.projects_proposable?
  nav.actions
    ul.list-inline
      li = link_to icon('plus', 'Submit a Project'), new_project_path, class: 'btn btn-default btn-sm' if can? :create, Project.new

h1.header
  = icon('users')
  span Projects

table.table.table-striped.table-bordered.table-condensed.hidden-sm.hidden-xs
  tr
    th Name
    th Tags
    th Comments
    th title="Application referencing this project as 1st choice" Applications (1st Choice)
    th title="Application referencing this project as 2nd choice" Applications (2nd Choice)
    th Status

  - @projects.each do |project|
    tr
      td
        = link_to project.name, project
        - if can? :crud, project
          .project-actions
            = link_to [:edit, project] do
              = icon('pencil')
            = link_to project, data: { confirm: 'This action cannot be undone. Are you sure?' }, method: :delete do
              = icon('minus')
      td = project_tags project
      td
        - if project.comments.any?
          = link_to project.comments.count, project_path(project, anchor: 'comments'), class: 'label label-default'
      td
        span.label.label-default title="Application still in draft mode"= project.first_choice_application_drafts.draft.count
        | /
        span.label.label-primary title="Applications sent in" = project.first_choice_application_drafts.applied.count
      td
        span.label.label-default title="Applications still in draft mode" = project.second_choice_application_drafts.draft.count
        | /
        span.label.label-primary title="Applications sent in" = project.second_choice_application_drafts.applied.count
      td = project_status project

- @projects.each do |project|
  table.table.table-striped.table-bordered.table-condensed.hidden-md.hidden-lg
    tr
      th Name
      td = link_to project.name, project
    - if can? :crud, project
      tr
        th Actions
        td 
          .project-actions
            = link_to [:edit, project] do
              = icon('pencil')
            = link_to project, data: { confirm: 'This action cannot be undone. Are you sure?' }, method: :delete do
              = icon('minus')
    tr
      th Tags
      td = project_tags project
    - if project.comments.any?
      tr
        th Comments
        td = link_to project.comments.count, project_path(project, anchor: 'comments'), class: 'label label-default'
    tr
      th title="Application referencing this project as 1st choice" Applications (1st Choice)
      td
        span.label.label-default title="Application still in draft mode"= project.first_choice_application_drafts.draft.count
        | /
        span.label.label-primary title="Applications sent in" = project.first_choice_application_drafts.applied.count
    tr
      th title="Application referencing this project as 2nd choice" Applications (2nd Choice)
      td
        span.label.label-default title="Applications still in draft mode" = project.second_choice_application_drafts.draft.count
        | /
        span.label.label-primary title="Applications sent in" = project.second_choice_application_drafts.applied.count
    tr
      th Status
      td = project_status project

app/views/projects/new.html.slim
= render "login_required" unless current_user

nav.page
  .back-nav
    ul
      li = icon('chevron-left')
      li = link_to 'All Projects', projects_path, class: 'back'

p.well Please make sure you have read our #{link_to "mentor guide", 'http://railsgirlssummerofcode.org/guide/projects/'} before you submit your Open Source project for the upcoming RGSoC.

= simple_nested_form_for @project, data: { js: "form-with-preview" } do |f|
  ul.nav.nav-tabs
      li.active
        a (href="#main-pane" data-toggle="tab") Project
      li
        a (href="#preview-pane" data-toggle="tab" id="preview-tab" onclick="sendPreview()" data-ajax-path=preview_projects_path) Preview

  .tab-content
    .tab-pane.active#main-pane

      - if @project.errors.any?
        #error_explanation
          h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
          ul
            - @project.errors.full_messages.each do |message|
              li = message

      = f.input :name, required: true, wrapper_html: { class: 'col-md-6' }, label: 'Project name'
      = f.input :mentor_name, required: true, wrapper_html: { class: 'col-md-6' }
      = f.input :mentor_github_handle, required: true, wrapper_html: { class: 'col-md-6' }
      = f.input :mentor_email, as: :email, required: true, wrapper_html: { class: 'col-md-6' }, hint: 'We will not share this publicly'
      = f.input :url, as: :url, wrapper_html: { class: 'col-md-6' }, label: "Project's website"
      = f.input :source_url, as: :url, wrapper_html: { class: 'col-md-6' }, label: "Repository", placeholder: 'Link to your source code (Github, Gitlab, Bitbucket, …)' 
      = f.input :description, wrapper_html: { class: 'col-md-6' }, placeholder: "What's your project about?", input_html: { rows: 5 }, hint: 'You can use basic <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a> here.'.html_safe
      = f.input :issues_and_features, wrapper_html: { class: 'col-md-6' }, placeholder: "How will the students be involved? What will they be working on? Possible features, maybe links to concrete issues on Github/Gitlab/Bitbucket/...", input_html: { rows: 5 }, hint: 'You can use basic <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a> here.'.html_safe
      = f.input :requirements, wrapper_html: { class: 'col-md-6' }, placeholder: "Skills students should have, ideally or as a hard requirement – e.g. good knowledge of a specific programming language, proficiency with CSS, etc. Maybe illustrate via a coding challenge that needs to be completed (on Exercism.io, Codeschool, Codewars or somewhere else).", input_html: { rows: 9 }, hint: 'You can use basic <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a> here.'.html_safe
      = f.input :taglist, wrapper_html: { class: 'col-md-6' }, placeholder: 'Languages, techniques, etc involved', label: 'Tags', hint: 'Separate tags by comma.'
      = f.input :license, wrapper_html: { class: 'col-md-6' }, input_html: { "data-licenses-src" => "/osi-licenses.json" }, placeholder: 'Enter the name of your open source license', hint: "See #{link_to "opensource.org", "https://opensource.org/licenses/alphabetical", target: '_blank'} for a list of OSI-approved licenses. #{mail_to "contact@rgsoc.org", "Contact us"} for dual licenses.".html_safe
      = f.input :code_of_conduct, as: :url, wrapper_html: { class: 'col-md-6' }, label: "Code Of Conduct", placeholder: "Link to your project's code of conduct"
      = f.input :beginner_friendly, wrapper_html: { class: 'col-md-6' }, label: 'Suitable for beginners?'
      .actions
        ul.list-inline
          - if current_user
            li = f.submit 'Submit', class: 'btn btn-success'
          - else
            li = f.submit 'Submit', class: 'btn btn-success', disabled: 'disabled'
    
    .tab-pane#preview-pane

app/views/projects/receipt.html.slim
h1 Hello, #{@project.submitter.name}!
p
  | Thank you for submitting your project #{@project.name} for RGSoC #{@project.season.year}! We will review it in the upcoming days and get back to you if we have any questions or feedback.

p
  | Don't hesitate to contact us though if you have any questions:
    #{mail_to 'contact@rgsoc.org'}

h3 What do you want to do next?

.back-nav
  ul
    li = icon('chevron-left')
    li = link_to 'View all projects', projects_path, class: 'back'
  ul
    li = icon('chevron-left')
    li = link_to 'View your submission', project_path(@project), class: 'back'

app/views/projects/show.html.slim
- content_for :title do
  = [@project.name, @project.season.try(:name)].compact.join(' – ')

nav.page
  .back-nav
    ul
      li = icon('chevron-left')
      li = link_to 'All Projects', projects_path, class: 'back'

= content_tag :h1, @project.name

- if can? :edit, @project
  nav.btn-group
    = link_to 'Edit', edit_project_path(@project), class: 'edit btn btn-default btn-small'
    = link_to 'Destroy', project_path(@project), method: :delete, data: { confirm: 'This action cannot be undone. Are you sure?' }, class: 'edit btn btn-default btn-small'
  p

table.table.table-striped.table-bordered
  tr
    th Mentor
    td
      = link_to @project.mentor_name, @project.mentor rescue @project.mentor_name
      = " ("
      = link_to @project.mentor_github_handle, "https://github.com/#{@project.mentor_github_handle}", class: 'github'
      |)
  tr
    th Project Website
    td = link_to @project.url, @project.url
  tr
    th Project Repository
    td = link_to @project.source_url, @project.source_url
  tr
    th Suitable for Beginners?
    td = @project.beginner_friendly? ? 'yes' : 'no'
  tr
    th Tags
    td = project_tags @project
  tr
    th State
    td = project_status(@project)
  tr
    th Applications (1st Choice)
    td = @project.first_choice_application_drafts.count
  tr
    th Applications (2nd Choice)
    td = @project.second_choice_application_drafts.count
  tr
    th Code of Conduct
    td = link_to @project.code_of_conduct, @project.code_of_conduct
  tr
    th License
    td = @project.license

h2.header
  = icon('file')
  span Project Description
- if @project.description
  .projects
    p = render_markdown(@project.description).html_safe

h2.header
  = icon('check')
  span Project's Requirements
- if @project.requirements
  .projects
    p = render_markdown(@project.requirements).html_safe

h2.header
  = icon('list')
  span = Project.human_attribute_name(:issues_and_features).titleize
- if @project.issues_and_features
  .projects
    p = render_markdown(@project.issues_and_features).html_safe

h2#comments.header
  = icon('comments')
  span Comments
- if @project.comments_locked?
  p Comments for this project have been locked.
- elsif current_user
  = simple_form_for Comment.new(commentable: @project), url: comments_path do |f|
    .checks
      = f.error_notification

      .form-inputs.clearfix
        = f.input :commentable_id, as: :hidden
        = f.input :commentable_type, as: :hidden
        = f.input :text, as: :text, label: "Comment on this project", input_html: { rows: 5 }, hint: 'You can use basic <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a> here.'.html_safe, required: true

      .form-actions
        = f.button :submit, 'Save comment'
- else
  p You must be logged in to comment on this project.

- @project.comments.each do |comment|
  hr(id="#{dom_id comment}")
  h5 = "#{ user_for_comment(comment) }, #{ l(comment.created_at, format: :short) }".html_safe
  p = render_markdown(comment.text).html_safe